title: Paul Elliot | Product Designer and Illustrator Glasgow  # Name of the site
author:
name: Paul Elliot                          # Default author name
email: 'info@paulelliot.co.uk'             # Default author email
metadata:
  description: 'UX/UI designer, illustrator and front end developer from Glasgow, working at FanDuel. Previously at digital agency NSDesign. Mobile app design Glasgow. Digital illustration Glasgow. Responsive web design and development Glasgow. I create engaging, intuitive, results-driven user interfaces and digital experiences across web and mobile.'               # Site description
  robots: 'noodp,noydir'
  og:locale: 'en_GB'
  og:type: 'website'
  og:image: ''
  og:title:  'Paul Elliot | Product Designer and Illustrator Glasgow'
  og:description: 'Glasgow based product designer and illustrator. Mobile app design, illustration, responsive web design and development Glasgow.'
  og:url: 'https://www.paulelliot.co.uk/'
  og:site_name: 'Paul Elliot'
  twitter:card: ''
  twitter:title: 'Paul Elliot | Product Designer and Illustrator Glasgow'
  twitter:description: 'Glasgow based product designer and illustrator. Mobile app design, illustration, responsive web design and development Glasgow.'
  twitter:image: ''
  generator: ''  # Disable Grav mention


