absolute_urls: false

home:
  alias: '/home'

pages:
  theme: paul-folio
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true                 # If true, enables the CSS pipeline, combining multiple CSS resources into one
  css_pipeline_include_externals: true # Include external CSS resources from the pipeline
  css_pipeline_before_excludes: true   # Renders pipelined CSS resources before non-pipelined CSS resources
  css_minify: true                     # Minify the CSS during pipelining
  css_minify_windows: true             # If false, blocks minifying on Windows servers
  css_rewrite: true                    # Rewrite any CSS relative URLs during pipelining



  js_pipeline: true
  js_minify: true 

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
